### ISSUE TITLE
Сертификат минцифры

### ISSUE THREAD

**Issue by deriglazoff** [maxineal/gost-stunnel#1]
Добрый день, нашли ваше великолепное решение. Но столкнулись с проблемой что наши сертификаты pfx в нем не работают, из-за корневого в цепочки от минцифры
![image](https://user-images.githubusercontent.com/99898300/227269925-db9ad36e-1481-4a0b-956d-c516e4d84a54.png)
другие сертификаты pfx без минцифр в цепочке работают без ошибок.
при попытке установить сертификат при сборке образа ловим ошибку прав
![image](https://user-images.githubusercontent.com/99898300/227269560-3f7f9422-18e5-4515-892d-a92ce457639c.png)

Подскажите, возможно вы уже столкнулись с этой проблемой и у вас есть решение?

**Comment by maxineal** [comment]
Привет! Нет, я с такой проблемой не сталкивался.
Но беглый гуглеж показал, что под рутом надо ставить в mRoot вместо uRoot.
Ссылка ниже с деталями:
https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=15079
--
Отправлено из Mail.ru для Android четверг, 23 марта 2023г., 19:28 +03:00 от Vlad  ***@***.*** :

**Comment by deriglazoff** [comment]
> Привет! Нет, я с такой проблемой не сталкивался. Но беглый гуглеж показал, что под рутом надо ставить в mRoot вместо uRoot. Ссылка ниже с деталями: https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=15079 -- Отправлено из Mail.ru для Android четверг, 23 марта 2023г., 19:28 +03:00 от Vlad ***@***.*** :
> […](#)
> Добрый день, нашли ваше великолепное решение. Но столкнулись с проблемой что наши сертификаты pfx в нем не работают, из-за корневого в цепочки от минцифры другие сертификаты pfx без минцифр в цепочке работают без ошибок. при попытке установить сертификат при сборке образа ловим ошибку прав Подскажите, возможно вы уже столкнулись с этой проблемой и у вас есть решение? — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you are subscribed to this thread. Message ID: @ github . com>

Да, действительно, спасибо! решили вставить в ваш образ сборку корневых сертификатов из https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/407/0/oshibk-ne-udetsja-postroit-cepochku-sertifiktov-dlja-doverennogo-kornevogo-centr-0x800b010a
